# Python 3.13
# conversion_table.py - 21/07/2025
# The file contains three essential conversion tables to implement in the tariff algorithm.

# The dictionary below is a complete mapping of US trade agreements, which is created by scraping the gov website - Programs section.
# Transforming it in a JSON file is unfeasible because JSON format does not accept backticks, which are necessary to match countries in the data sets.

tas = {'SG':['Singapore'],
 'S+':['Canada', 'Mexico'],
 'S':['Canada', 'Mexico'],
 'R':['Barbados', 'Belize', 'Curaçao', 'Guyana', 'Haiti', 'Jamaica', 'Saint Lucia', 'Trinidad and Tobago'],
 'PE':['Peru'],
 'PA':['Panama'],
 'P+':['Costa Rica', 'Dominican Republic', 'El Salvador', 'Guatemala', 'Honduras', 'Nicaragua'],
 'P':['Costa Rica', 'Dominican Republic', 'El Salvador', 'Guatemala', 'Honduras', 'Nicaragua'],
 'OM':['Oman'],
 'MX':['Mexico'],
 'MA':['Morocco'],
 'KR':['South Korea', "Korea, Republic of"],
 'JP':['Japan'],
 'JO':['Jordan'],
 'IL': ['Israel'],
 'E':['Antigua and Barbuda', 'Aruba', 'Bahamas', 'Barbados', 'Belize', 'British Virgin Islands', 'Curaçao', 'Dominica',
      'Grenada', 'Guyana', 'Haiti', 'Jamaica', 'Montserrat', 'Saint Kitts and Nevis',
      'Saint Lucia', 'Saint Vincent and the Grenadines', 'Trinidad and Tobago'],
 'E*':['Antigua and Barbuda', 'Aruba', 'Bahamas', 'Barbados', 'Belize', 'British Virgin Islands', 'Curaçao', 'Dominica',
      'Grenada', 'Guyana', 'Haiti', 'Jamaica', 'Montserrat', 'Saint Kitts and Nevis',
      'Saint Lucia', 'Saint Vincent and the Grenadines', 'Trinidad and Tobago'],
 'D':['Angola', 'Benin', 'Botswana', 'Burkina Faso', 'Cabo Verde', 'Central African Republic', 'Chad', 'Comoros',
      "Côte d`Ivoire", 'Democratic Republic of the Congo', 'Djibouti', 'Eswatini', 'Ethiopia', 'Gabon',
      'Gambia', 'Ghana', 'Guinea', 'Guinea-Bissau', 'Kenya', 'Lesotho', 'Liberia', 'Madagascar', 'Malawi', 'Mali',
      'Mauritius', 'Mozambique', 'Namibia', 'Niger', 'Nigeria', 'Republic of the Congo', 'Rwanda', 'Senegal',
      'Sierra Leone', 'South Africa', 'São Tomé and Príncipe', 'Tanzania', 'Togo', 'Uganda', 'Zambia'],
 'CO':['Colombia'],
 'CL':['Chile'],
 'CA':['Canada'],
 'BH':['Bahrain'],
 'B':['Canada'],
 'AU':['Australia'],
 'A+':["Afghanistan", "Angola", "Benin", "Bhutan", "Burkina Faso", "Burundi", "Cambodia",
    "Central African Republic", "Chad", "Comoros", "Democratic Republic of the Congo",
    "Djibouti", "Ethiopia", "Gambia", "Guinea", "Guinea-Bissau", "Haiti", "Kiribati",
    "Lesotho", "Liberia", "Madagascar", "Malawi", "Mali", "Mauritania", "Mozambique",
    "Myanmar", "Nepal", "Niger", "Rwanda", "Samoa", "Senegal", "Sierra Leone",
    "Solomon Islands", "Somalia", "South Sudan", "São Tomé and Príncipe", "Tanzania",
    "Timor-Leste", "Togo", "Tuvalu", "Uganda", "Vanuatu", "Yemen", "Zambia"],
 'A':[
    "Afghanistan", "Albania", "Algeria", "Angola", "Anguilla", "Argentina", "Armenia",
    "Azerbaijan", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana",
    "Brazil", "British Indian Ocean Territory", "British Virgin Islands", "Burkina Faso",
    "Burundi", "Cabo Verde", "Cambodia", "Cameroon", "Central African Republic", "Chad",
    "Christmas Island", "Cocos (Keeling) Islands", "Comoros", "Cook Islands", "Côte d`Ivoire",
    "Democratic Republic of the Congo", "Djibouti", "Dominica", "Ecuador", "Egypt", "Eritrea",
    "Eswatini (Swaziland)", "Ethiopia", "Falkland Islands", "Fiji", "Gabon", "Gambia",
    "Gaza Strip", "Georgia", "Ghana", "Grenada", "Guinea", "Guinea-Bissau", "Guyana", "Haiti",
    "Heard and McDonald Islands", "Indonesia", "Iraq", "Jamaica", "Jordan", "Kazakhstan", "Kenya",
    "Kiribati", "Kosovo", "Kyrgyzstan", "Lebanon", "Lesotho", "Liberia", "Madagascar", "Malawi",
    "Maldives", "Mali", "Mauritania", "Mauritius", "Moldova", "Mongolia", "Montenegro",
    "Montserrat", "Mozambique", "Myanmar (Burma)", "Namibia", "Nepal", "Niger", "Nigeria", "Niue",
    "Norfolk Island", "North Macedonia", "Pakistan", "Papua New Guinea", "Paraguay", "Philippines",
    "Pitcairn Islands", "Republic of the Congo", "Rwanda", "Saint Helena", "Saint Lucia",
    "Saint Vincent and the Grenadines", "Samoa", "Senegal", "Serbia", "Sierra Leone",
    "Solomon Islands", "Somalia", "South Africa", "South Sudan", "Sri Lanka", "Suriname",
    "São Tomé and Príncipe", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tokelau", "Tonga",
    "Tunisia", "Tuvalu", "Uganda", "Ukraine", "Uzbekistan", "Vanuatu", "Wallis and Futuna",
    "West Bank", "Western Sahara", "Yemen", "Zambia", "Zimbabwe"],
 'A*':['Afghanistan', 'Angola', 'Benin', 'Bhutan', 'Burkina Faso', 'Burundi', 'Cambodia',
        'Central African Republic', 'Chad', 'Comoros', 'Democratic Republic of the Congo', 'Djibouti',
        'Eritrea', 'Ethiopia', 'Gambia', 'Guinea', 'Guinea-Bissau', 'Haiti', 'Kiribati', 'Laos', 'Lesotho',
        'Liberia', 'Madagascar', 'Malawi', 'Mali', 'Mauritania', 'Mozambique', 'Myanmar', 'Nepal', 'Niger',
        'Rwanda', 'Senegal', 'Sierra Leone', 'Solomon Islands', 'Somalia', 'South Sudan', 'Sudan', 'Tanzania',
        'Timor-Leste', 'Togo', 'Tuvalu', 'Uganda', 'Vanuatu', 'Yemen', 'Zambia'],
 'MFN': [
    "Afghanistan", "Albania", "Andorra", "Angola", "Anguilla", "Antigua and Barbuda", "Argentina",
    "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh",
    "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bhutan", "Bolivia",
    "Bosnia and Herzegovina", "Botswana", "Brazil", "British Indian Ocean Territory",
    "British Virgin Islands", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde",
    "Cambodia", "Cameroon", "Canada", "Cayman Islands", "Central African Republic", "Chad",
    "Chile", "China", "Christmas Island", "Cocos (Keeling) Islands", "Colombia", "Comoros",
    "Cook Islands", "Costa Rica", "Croatia", "Cyprus", "Czechia (Czech Republic)",
    "Côte d`Ivoire", "Democratic Republic of the Congo", "Denmark", "Djibouti",
    "Dominica", "Dominican Republic", "East Germany", "Ecuador", "Egypt", "El Salvador",
    "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia",
    "Ethiopia prior to Eritrea split", "Falkland Islands", "Faroe Islands", "Fiji", "Finland",
    "France", "French Guiana", "French Polynesia", "French Southern and Antarctic Lands", "Gabon",
    "Gambia", "Gaza Strip", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece", "Greenland",
    "Grenada", "Guadeloupe", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti",
    "Heard and McDonald Islands", "Honduras", "Hong Kong", "Hungary", "Iceland", "India",
    "Indonesia", "Internat Organization", "Iran", "Iraq", "Ireland", "Israel", "Israel prior to 1989",
    "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kosovo", "Kuwait",
    "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein",
    "Lithuania", "Luxembourg", "Macau", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali",
    "Malta", "Marshall Islands", "Martinique", "Mauritania", "Mauritius", "Mayotte", "Mexico",
    "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Montserrat", "Morocco",
    "Mozambique", "Myanmar (Burma)", "Namibia", "Nauru", "Nepal", "Netherlands",
    "New Caledonia", "New Zealand", "Nicaragua", "Niger", "Nigeria",
    "Niue", "Norfolk Island", "North Macedonia", "Norway", "Oman", "Pakistan", "Palau", "Panama",
    "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Pitcairn Islands", "Poland", "Portugal",
    "Puerto Rico/US", "Qatar", "Republic of the Congo", "Reunion", "Romania", "Russia", "Rwanda",
    "Saint Helena", "Saint Kitts and Nevis", "Saint Lucia", "Saint Pierre and Miquelon",
    "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Saudi Arabia",
    "Saudi Arabian-Iraqi neutral zone", "Senegal", "Serbia", "Serbia and Montenegro",
    "Serbia prior to 2009", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia",
    "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan", "South Yemen",
    "Soviet Union", "Spain", "Sri Lanka", "Sudan", "Sudan prior to South Sudan split", "Suriname",
    "Svalbard and Jan Mayen", "Sweden", "Switzerland", "Syria", "São Tomé and Príncipe", "Taiwan",
    "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tokelau", "Tonga", "Transshipment",
    "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Turks and Caicos Islands", "Tuvalu",
    "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "Unspecified", "Uruguay",
    "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Wallis and Futuna",
    "West Bank", "Western Sahara", "Yemen", "Zambia", "Zimbabwe"],
 'L': [
    "Afghanistan", "Albania", "Andorra", "Angola", "Anguilla", "Antigua and Barbuda", "Argentina",
    "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh",
    "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bhutan", "Bolivia",
    "Bosnia and Herzegovina", "Botswana", "Brazil", "British Indian Ocean Territory",
    "British Virgin Islands", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde",
    "Cambodia", "Cameroon", "Canada", "Cayman Islands", "Central African Republic", "Chad",
    "Chile", "China", "Christmas Island", "Cocos (Keeling) Islands", "Colombia", "Comoros",
    "Cook Islands", "Costa Rica", "Croatia", "Cyprus", "Czechia (Czech Republic)",
    "Côte d`Ivoire", "Democratic Republic of the Congo", "Denmark", "Djibouti",
    "Dominica", "Dominican Republic", "East Germany", "Ecuador", "Egypt", "El Salvador",
    "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia",
    "Ethiopia prior to Eritrea split", "Falkland Islands", "Faroe Islands", "Fiji", "Finland",
    "France", "French Guiana", "French Polynesia", "French Southern and Antarctic Lands", "Gabon",
    "Gambia", "Gaza Strip", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece", "Greenland",
    "Grenada", "Guadeloupe", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti",
    "Heard and McDonald Islands", "Honduras", "Hong Kong", "Hungary", "Iceland", "India",
    "Indonesia", "Internat Organization", "Iran", "Iraq", "Ireland", "Israel", "Israel prior to 1989",
    "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kosovo", "Kuwait",
    "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein",
    "Lithuania", "Luxembourg", "Macau", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali",
    "Malta", "Marshall Islands", "Martinique", "Mauritania", "Mauritius", "Mayotte", "Mexico",
    "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Montserrat", "Morocco",
    "Mozambique", "Myanmar (Burma)", "Namibia", "Nauru", "Nepal", "Netherlands",
    "New Caledonia", "New Zealand", "Nicaragua", "Niger", "Nigeria",
    "Niue", "Norfolk Island", "North Macedonia", "Norway", "Oman", "Pakistan", "Palau", "Panama",
    "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Pitcairn Islands", "Poland", "Portugal",
    "Puerto Rico/US", "Qatar", "Republic of the Congo", "Reunion", "Romania", "Russia", "Rwanda",
    "Saint Helena", "Saint Kitts and Nevis", "Saint Lucia", "Saint Pierre and Miquelon",
    "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Saudi Arabia",
    "Saudi Arabian-Iraqi neutral zone", "Senegal", "Serbia", "Serbia and Montenegro",
    "Serbia prior to 2009", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia",
    "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan", "South Yemen",
    "Soviet Union", "Spain", "Sri Lanka", "Sudan", "Sudan prior to South Sudan split", "Suriname",
    "Svalbard and Jan Mayen", "Sweden", "Switzerland", "Syria", "São Tomé and Principe", "Taiwan",
    "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tokelau", "Tonga", "Transshipment",
    "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Turks and Caicos Islands", "Tuvalu",
    "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "Unspecified", "Uruguay",
    "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Wallis and Futuna",
    "West Bank", "Western Sahara", "Yemen", "Zambia", "Zimbabwe"],
 'K': [
    "Afghanistan", "Albania", "Andorra", "Angola", "Anguilla", "Antigua and Barbuda", "Argentina",
    "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh",
    "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bhutan", "Bolivia",
    "Bosnia and Herzegovina", "Botswana", "Brazil", "British Indian Ocean Territory",
    "British Virgin Islands", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde",
    "Cambodia", "Cameroon", "Canada", "Cayman Islands", "Central African Republic", "Chad",
    "Chile", "China", "Christmas Island", "Cocos (Keeling) Islands", "Colombia", "Comoros",
    "Cook Islands", "Costa Rica", "Croatia", "Cyprus", "Czechia (Czech Republic)",
    "Côte d`Ivoire", "Democratic Republic of the Congo", "Denmark", "Djibouti",
    "Dominica", "Dominican Republic", "East Germany", "Ecuador", "Egypt", "El Salvador",
    "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia",
    "Ethiopia prior to Eritrea split", "Falkland Islands", "Faroe Islands", "Fiji", "Finland",
    "France", "French Guiana", "French Polynesia", "French Southern and Antarctic Lands", "Gabon",
    "Gambia", "Gaza Strip", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece", "Greenland",
    "Grenada", "Guadeloupe", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti",
    "Heard and McDonald Islands", "Honduras", "Hong Kong", "Hungary", "Iceland", "India",
    "Indonesia", "Internat Organization", "Iran", "Iraq", "Ireland", "Israel", "Israel prior to 1989",
    "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kosovo", "Kuwait",
    "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein",
    "Lithuania", "Luxembourg", "Macau", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali",
    "Malta", "Marshall Islands", "Martinique", "Mauritania", "Mauritius", "Mayotte", "Mexico",
    "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Montserrat", "Morocco",
    "Mozambique", "Myanmar (Burma)", "Namibia", "Nauru", "Nepal", "Netherlands",
    "New Caledonia", "New Zealand", "Nicaragua", "Niger", "Nigeria",
    "Niue", "Norfolk Island", "North Macedonia", "Norway", "Oman", "Pakistan", "Palau", "Panama",
    "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Pitcairn Islands", "Poland", "Portugal",
    "Puerto Rico/US", "Qatar", "Republic of the Congo", "Reunion", "Romania", "Russia", "Rwanda",
    "Saint Helena", "Saint Kitts and Nevis", "Saint Lucia", "Saint Pierre and Miquelon",
    "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Saudi Arabia",
    "Saudi Arabian-Iraqi neutral zone", "Senegal", "Serbia", "Serbia and Montenegro",
    "Serbia prior to 2009", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia",
    "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan", "South Yemen",
    "Soviet Union", "Spain", "Sri Lanka", "Sudan", "Sudan prior to South Sudan split", "Suriname",
    "Svalbard and Jan Mayen", "Sweden", "Switzerland", "Syria", "São Tomé and Principe", "Taiwan",
    "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tokelau", "Tonga", "Transshipment",
    "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Turks and Caicos Islands", "Tuvalu",
    "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "Unspecified", "Uruguay",
    "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Wallis and Futuna",
    "West Bank", "Western Sahara", "Yemen", "Zambia", "Zimbabwe"],
 'C': [
    "Afghanistan", "Albania", "Andorra", "Angola", "Anguilla", "Antigua and Barbuda", "Argentina",
    "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh",
    "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bhutan", "Bolivia",
    "Bosnia and Herzegovina", "Botswana", "Brazil", "British Indian Ocean Territory",
    "British Virgin Islands", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde",
    "Cambodia", "Cameroon", "Canada", "Cayman Islands", "Central African Republic", "Chad",
    "Chile", "China", "Christmas Island", "Cocos (Keeling) Islands", "Colombia", "Comoros",
    "Cook Islands", "Costa Rica", "Croatia", "Cyprus", "Czechia (Czech Republic)",
    "Côte d`Ivoire", "Democratic Republic of the Congo", "Denmark", "Djibouti",
    "Dominica", "Dominican Republic", "East Germany", "Ecuador", "Egypt", "El Salvador",
    "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia",
    "Ethiopia prior to Eritrea split", "Falkland Islands", "Faroe Islands", "Fiji", "Finland",
    "France", "French Guiana", "French Polynesia", "French Southern and Antarctic Lands", "Gabon",
    "Gambia", "Gaza Strip", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece", "Greenland",
    "Grenada", "Guadeloupe", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti",
    "Heard and McDonald Islands", "Honduras", "Hong Kong", "Hungary", "Iceland", "India",
    "Indonesia", "Internat Organization", "Iran", "Iraq", "Ireland", "Israel", "Israel prior to 1989",
    "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kosovo", "Kuwait",
    "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein",
    "Lithuania", "Luxembourg", "Macau", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali",
    "Malta", "Marshall Islands", "Martinique", "Mauritania", "Mauritius", "Mayotte", "Mexico",
    "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Montserrat", "Morocco",
    "Mozambique", "Myanmar (Burma)", "Namibia", "Nauru", "Nepal", "Netherlands",
    "New Caledonia", "New Zealand", "Nicaragua", "Niger", "Nigeria",
    "Niue", "Norfolk Island", "North Macedonia", "Norway", "Oman", "Pakistan", "Palau", "Panama",
    "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Pitcairn Islands", "Poland", "Portugal",
    "Puerto Rico/US", "Qatar", "Republic of the Congo", "Reunion", "Romania", "Russia", "Rwanda",
    "Saint Helena", "Saint Kitts and Nevis", "Saint Lucia", "Saint Pierre and Miquelon",
    "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Saudi Arabia",
    "Saudi Arabian-Iraqi neutral zone", "Senegal", "Serbia", "Serbia and Montenegro",
    "Serbia prior to 2009", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia",
    "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan", "South Yemen",
    "Soviet Union", "Spain", "Sri Lanka", "Sudan", "Sudan prior to South Sudan split", "Suriname",
    "Svalbard and Jan Mayen", "Sweden", "Switzerland", "Syria", "São Tomé and Principe", "Taiwan",
    "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tokelau", "Tonga", "Transshipment",
    "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Turks and Caicos Islands", "Tuvalu",
    "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "Unspecified", "Uruguay",
    "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Wallis and Futuna",
    "West Bank", "Western Sahara", "Yemen", "Zambia", "Zimbabwe"],
 'NP':['Nepal'],
 'TO':['Tunisia']}

# Essential dictionary when parsing tariff entries, in order to extract usable units of measure (for specific tariffs)

tariff_unit_to_description = {
    'kg': 'kilograms',
    'kilograms': 'kilograms',
    'net kg': 'clean yield kilograms',
    '1000 kg': 'metric tons',
    'gram': 'grams',
    'grams': 'grams',
    'g': 'grams',
    'gm': 'grams',
    'no': 'number',
    'no.': 'number',
    'each': 'pieces',
    'pcs': 'pieces',
    'piece': 'pieces',
    'doz': 'dozens',
    'dozen': 'dozens',
    'dozen pcs': 'dozen pieces',
    'dpc': 'dozen pieces',
    'dpr': 'dozen pairs',
    'pr': 'pairs',
    'prs': 'pairs',
    'pr.': 'pairs',
    'pair': 'pairs',
    'pairs': 'pairs',
    'set': 'kits',
    'kit': 'kits',
    'bbl': 'barrels',
    'barrel': 'barrels',
    'bbls': 'barrels',
    'l': 'liters',
    'ltr': 'liters',
    'liters': 'liters',
    'm2': 'square meters',
    'm²': 'square meters',
    'sq. m': 'square meters',
    'm3': 'cubic meters',
    'm³': 'cubic meters',
    'clean kg': 'clean yield kilograms',
    'clean kilogram': 'clean yield kilograms',
    'cyk': 'clean yield kilograms',
    't': 'metric tons',
    'ton': 'metric tons',
    'tons': 'metric tons',
    'ct': 'carats',
    'ct.': 'carats',
    'carat': 'carats',
    'carats': 'carats',
    'pf.l': 'proof liters',
    'pf.liter': 'proof liters',
    'pf ltr': 'proof liters',
    'pfl': 'proof liters',
    'fbm': 'foot, board measure',
    'sq': 'squares',
    'square': 'squares',
    'square meter': 'square meters',
    'cm2': 'square centimeters',
    'linear meter': 'fiber meters',
    'lnm': 'fiber meters',
    'km': 'kilometers',
    'km3': 'thousands of cubic meters',
    'thousand': 'thousand units',
    '1000': 'thousand units',
    'thousand meters': 'kilometers',
    'gross': 'gross',
    'gross lines': 'gross',
    'pack': 'pack',
    'pk': 'pack',
    'dose': 'doses',
    'doses': 'doses',
    'kwh': 'kilowatt hours',
    'kwhs': 'kilowatt hours',
    'megawatt hours': 'megawatt hours',
    'jewel': 'jewels',
    'jewels': 'jewels',
}

# Essential for converting between units of measure (e.g. allow 'dozen' to be convertible into 'number')
unit_conversion_map = {
    ('number', 'dozen'): 1 / 12,
    ('pcs', 'dozen'): 1 / 12,
    ('prs', 'dpr'): 1 / 12,
    ('number', 'dpr'): 1 / 12,
    ('dozen', 'number'): 12,
    ('dpr', 'prs'): 12,
    ('gross', 'pcs'): 144,
    ('pcs', 'gross'): 1/144,
    ('thousand units', 'number'): 1000,
    ('thousand units', 'dozen'): 1000 / 12,
    ('thousand units', 'pcs'): 1000,
    ('thousand units', 'prs'): 1000,
    ('thousand units', 'dpr'): 1000 / 12,
    ('thousand units', 'gross'): 1000 / 144,
    ('number', 'thousand units'): 1 / 1000,
    ('dozen', 'thousand units'): 12 / 1000,
    ('pcs', 'thousand units'): 1 / 1000,
}